#Site Settings
title: Jekyll for Web Designers
email: your-email@domain.com
description: "Companion blog to the lynda.com course, Jekyll for Web Designers. 
  This site is designed to present Jekyll to web designers in a clear, concise way, and provide a resource and reference  for those that are new to Jekyll."
baseurl: "/jekyll-for-designers-lynda" 
url: "http://tonatiuh8.github.io/jekyll-for-designers-lynda" 
tagline: "A basic guide to Jekyll"


# Build Settings
markdown: kramdown
theme: minima
paginate: 4
paginate_path: '/blog/pages:num/'
gems: [jekyll-paginate]