#Site Settings
title: TonaBoy's Blog
email: your-email@domain.com
description: "Companion blog to the lynda.com course, Jekyll for Web Designers. 
  This site is designed to present Jekyll to web designers in a clear, concise way, and provide a resource and reference  for those that are new to Jekyll."
baseurl: "/jekyll-for-designers-lynda" 
url: "http://tonatiuh8.github.io/jekyll-for-designers-lynda" 
tagline: "No tagling to see if git catches it"


# Build Settings
markdown: kramdown
kramdown:
    auto_ids: false
theme: minima
paginate: 4
paginate_path: '/myBlog2/page:num/'
gems: [jekyll-paginate]
permalink: /myBlog2/:title
